import os
import time

blue = '\033[34;1m'
green = '\033[32;1m'
purple = '\033[35;1m'
cyan = '\033[36;1m'
red = '\033[31;1m'
white = '\033[37;1m'
yellow = '\033[33;1m'

os.system ('clear')

print(yellow),"   ______________________________________________"
time.sleep(0.23)
print(red),"   |____________________________________________|"
time.sleep(0.24)
print(purple),"   |   /\      /\------Author------/\      /\   |"
time.sleep(0.24)
print(blue),"   |  /!!\    /!!\  4RY4N0 - D3V1L  /??\    /??\  |"
time.sleep(0.24)
print(green),"   | /!!!!\  /!!!!\   >>>   <<<   /????\  /????\ |"
time.sleep(0.24)
print(yellow),"   |/______\/______\____________/______\/______\|"
time.sleep (2.2)
print("\n")
print(red),("[1 ]install--MBF")
print(yellow),("[2 ]install--LITEDDOS")
print(green),("[3 ]install--LITESCRIPT")
print(blue),("[4 ]install--BAJINGANv6 ")
print(white),("[5 ]install--OSIF")
print(purple),("[6 ]install--RED_HAWK")
print(red),("[7 ]install--weeman")
print(yellow),("[8 ]install--PhisingGame")
print(green),("[9 ]install--NewscatBOT")
print(blue),("[10]install--kubik-bot")
print(white),("[11]install--sqlmap")
print(purple),("[12]install--KumpulanFbbrute")
print(red),("[13]install--LITESPAM")
print(yellow),("[14]install--MCR")
print(green),("[15]install--mantan.py")
print(blue),("[16]install--BotKomema")
print(white),("[17]install--diejoubu")
print(purple),("[18]install--ipcs")
print(red),("[19]install--FB-React")
print(yellow),("[20]install--MancingNew")
print(green),("[21]install--TembakXL")
print(blue),("[22]install--TUANB4DUTv3")
print(white),("[23]install--BlackNmap")
print(purple),("[24]install--vbscan")
print(red),("[25]install--Tool-X")

print(white),("[0 ]Exit--Exit The Program")
print(yellow),("[+]------------------------------------------------[-]")
print(green),"[ Script By:",(blue),"Termux/Programing Tools & app berfaedah]"
print(green),"[ Since    :",(white),"20 Oktober 2018                        ]"
print(green),"[ Support  :",(yellow),"All who have liked the page            ]"
print(yellow),("[+]------------------------------------------------[-]")
pilih = input(" Pilih No: ")

if pilih ==0:
    time.sleep(0.5)
    print(green),("Thanks To:")
    time.sleep (1.4)
    print(blue),("Admin Termux/Programing Tools & app berfaedah")
    time.sleep (1.9)
    print(yellow),("We Are Newbie")
    time.sleep (1.5)
    print(green),("Kalo kalian ga bisa bikin script kyk gini...")
    time.sleep (1.9)
    print(red),("Belajarlah Bahasa Pemograman!")
    time.sleep (1.95)
    print(blue),("Bukan Kode-Kodean di FB!")
    time.sleep (1.9)
if pilih ==1:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install python2')
    os.system ('pip2 install mechanize')
    os.system ('pip2 install --upgrade pip')
    os.system ('git clone https://github.com/YukersCreew/mbf')
    os.chdir ('mbf')
    os.system ('clear')
    os.system ('python2 MBF.py')
if pilih ==2:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install python2')
    os.system ('git clone https://github.com/4L13199/LITEDDOS')
    os.chdir ('LITEDDOS')
    os.system ('clear')
    print (yellow)
    print ("Jalankan dg ketik perintah:")
    time.sleep(2.0)
    print ("$ cd LITEDDOS")
    time.sleep(2.0)
    print ("$ python2 LITEDDOS.py <ip> <port> <packet>")
if pilih ==3:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install python2')
    os.system ('git clone https://github.com/4L13199/LITESCRIPT')
    os.chdir ('LITESCRIPT')
    os.system ('clear')
    os.system ('python2 LITESCRIPT.py')

if pilih ==4:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pip2 install --upgrade pip')
    os.system ('pip2 install termcolor')
    os.system ('pip2 install lolcat')
    os.system ('apt install toilet')
    os.system ('git clone https://github.com/DarknessCyberTeam/BAJINGANv6')
    os.chdir ('BAJINGANv6')
    os.system ('clear')
    print(green),('inget!')
    print(red),('Username: BAJINGAN')
    print(red),('Password: Gans')
    time.sleep (5.5)
    os.system ('sh BAJINGAN.sh')
if pilih ==5:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pip2 install --upgrade pip')
    os.system ('pip2 install requests mechanize')
    os.system ('git clone https://github.com/CiKu370/OSIF')
    os.chdir ('OSIF')
    os.system ('pip2 install -r requirements.txt')
    os.system ('clear')
    print(red),('ketik token (untuk login fb)')
    time.sleep(1.0)
    print(red),('ketik help (untuk melihat bantuan)')
    time.sleep(1.5)
    os.system ('python2 osif.py')
if pilih ==6:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install php')
    os.system ('pkg install curl')
    os.system ('git clone https://github.com/Tuhinshubhra/RED_HAWK')
    os.chdir ('RED_HAWK')
    os.system ('clear')
    os.system ('php rhawk.php')
if pilih ==7:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt-get update')
    os.system ('apt-get upgrade')
    os.system ('git clone https://github.com/evait-security/weeman')
    os.chdir ('weeman')
    os.system ('clear')
    os.system ('python2 weeman.py')
if pilih ==8:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('git clone https://github.com/Senitopeng/PhisingGame')
    os.chdir ('PhisingGame')
    os.system ('clear')
    os.system ('python2 phising.py')
if pilih ==9:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade && apt install python2 && apt install curl && apt install wget && apt install bash && apt install grep')
    os.system ('git clone https://github.com/kadalsinus/NewscatBOT')
    os.chdir ('NewscatBOT')
    os.system ('chmod +x BOT.sh')
    os.system ('clear')
    os.system ('sh BOT.sh')
if pilih ==10:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install php')
    os.system ('git clone https://github.com/radenvodka/kubik-bot')
    os.chdir ('kubik-bot')
    os.system ('pkg install nano')
    os.system ('nano kubik.php')
if pilih ==11:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('git clone https://github.com/sqlmapproject/sqlmap.git')
    os.chdir ('sqlmap')
    os.system ('chmod +x sqlmap.py && chmod +x sqlmapapi.py')
    os.system ('clear')
    print(blue),('jalankan dg perintah:')
    time.sleep (1.7)
    print(blue),('cd sqlmap')
    print(blue),('python2 sqlmap.py -u <web vuln>')
if pilih ==12:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade -y')
    os.system ('pkg install php')
    os.system ('pip2 install --upgrade pip')
    os.system ('pip2 install mechanize')
    os.system ('git clone https://github.com/Senitopeng/KumpulanFbbrute.git')
    os.chdir ('KumpulanFbbrute')
    os.system ('clear')
    os.system ('python2 jomblo.py')
if pilih ==13:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('pkg update && pkg upgrade')
    os.system ('pkg install php')
    os.system ('pkg install toilet')
    os.system ('git clone https://github.com/4L13199/LITESPAM')
    os.chdir ('LITESPAM')
    os.system ('clear')
    os.system ('sh LITESPAM.sh')
if pilih ==14:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('pkg update && pkg upgrade')
    os.system ('git clone https://github.com/iqbalfaf/MCT')
    os.chdir ('MCT')
    os.system ('chmod +x install.sh')
    os.system ('clear')
    os.system ('sh install.sh')
if pilih ==15:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('apt install php')
    os.system ('apt install nano')
    os.system ('pip2 install --upgrade pip')
    os.system ('pip2 install requests')
    os.system ('git clone https://github.com/Senitopeng/SpamSms.git')
    os.chdir ('SpamSms')
    os.system ('chmod +x mantan.py')
    os.system ('clear')
    os.system ('python2 mantan.py')
if pilih ==16:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pip2 install --upgrade pip2')
    os.system ('pip2 install mechanize')
    os.system ('git clone https://github.com/Senitopeng/Botkomena')
    os.chdir ('Botkomena')
    os.system ('clear')
    os.system ('python2 botkomena.py')
if pilih ==17:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('pkg update && pkg upgrade')
    os.system ('apt install php')
    os.system ('git clone https://github.com/alintamvanz/diejoubu')
    os.chdir ('diejoubu')
    os.chdir ('v1.2')
    os.system ('clear')
    os.system ('php daijobu.php')
if pilih ==18:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pip2 install requests')
    os.system ('git clone https://github.com/kancotdiq/ipcs')
    os.chdir ('ipcs')
    os.system ('clear')
    os.system ('python2 scan.py')
if pilih ==19:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('apt install php curl -y')
    os.system ('git clone http://github.com/AMVengeance/FB-React.git')
    os.chdir ('FB-React')
    os.system ('chmod +x start')
    os.system ('clear')
    os.system ('./start')
if pilih ==20:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade -y')
    os.system ('apt install wget')
    os.system ('apt install ruby')
    os.system ('gem install lolcat')
    os.system ('wget https://github.com/Senitopeng/Mancing/raw/master/2/IMancingN ; python2 IMancingN')
    os.chdir ('mancingnew')
    os.system ('clear')
    os.system ('python2 listening.py')
if pilih ==21:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('git clone https://github.com/anggialberto/xl-py')
    os.chdir ('xl-py')
    os.system ('pip install --upgrade pip')
    os.system ('pip install -r requirements.txt')
    os.system ('chmod +x app.py')
    os.system ('clear')
    os.system ('python2 app.py')
if pilih ==22:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('apt install php && apt install curl')
    os.system ('apt install ruby')
    os.system ('gem install lolcat')
    os.system ('git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv3')
    os.chdir ('TOOLSINSTALLERv3')
    os.system ('chmod +x TUANB4DUT.sh')
    os.system ('clear')
    os.system ('sh TUANB4DUT.sh')
if pilih ==23:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('git clone https://github.com/Xi4u7/BlackNmap')
    os.chdir ('BlackNmap')
    os.system ('chmod +x blacknmap')
    os.system ('chmod 777 blacknmap')
    os.system ('clear')
    os.system ('sh blacknmap')
if pilih ==24:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade -y')
    os.system ('apt install perl')
    os.system ('git clone https://github.com/rezasp/vbscan')
    os.chdir ('vbscan')
    os.system ('ls')
    os.system ('clear')
    os.system ('perl vbscan.pl')
if pilih ==25:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('git clone https://github.com/Rajkumrdusad/Tool-X.git')
    os.chdir ('Tool-X')
    os.system ('chmod +x install.aex')
    os.system ('sh install.aex')
